// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRGgTpKhfMAHRHNKY1-b8GPJgYK54qmq0',
    appId: '1:814642971398:web:ed6d75c9e16c289ba65487',
    messagingSenderId: '814642971398',
    projectId: 'bee-store-itu34-ada54',
    authDomain: 'bee-store-itu34-ada54.firebaseapp.com',
    storageBucket: 'bee-store-itu34-ada54.appspot.com',
    measurementId: 'G-KNPWW83D0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjtrjhpomN3JO3DcHirpg_f_g6fTTnbJQ',
    appId: '1:814642971398:android:40f80b7757c59ee7a65487',
    messagingSenderId: '814642971398',
    projectId: 'bee-store-itu34-ada54',
    storageBucket: 'bee-store-itu34-ada54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOE9y8A8QfcGdFNutkp0czbNYHerRchbw',
    appId: '1:814642971398:ios:866a3b8de31eccc2a65487',
    messagingSenderId: '814642971398',
    projectId: 'bee-store-itu34-ada54',
    storageBucket: 'bee-store-itu34-ada54.appspot.com',
    iosBundleId: 'com.example.beeStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOE9y8A8QfcGdFNutkp0czbNYHerRchbw',
    appId: '1:814642971398:ios:560417bd99fb3061a65487',
    messagingSenderId: '814642971398',
    projectId: 'bee-store-itu34-ada54',
    storageBucket: 'bee-store-itu34-ada54.appspot.com',
    iosBundleId: 'com.example.beeStore.RunnerTests',
  );
}
